# Hedonic Pricing

We often try to predict the price of an asset from its observable characteristics. This is generally called **hedonic pricing**: How do the unit's characteristics determine its market price?

In the lab folder, there are three options: housing prices in pierce_county_house_sales.csv, car prices in cars_hw.csv, and airbnb rental prices in airbnb_hw.csv. If you know of another suitable dataset, please feel free to use that one.

1. Clean the data and perform some EDA and visualization to get to know the data set.
2. Transform your variables --- particularly categorical ones --- for use in your regression analysis.
3. Implement an ~80/~20 train-test split. Put the test data aside.
4. Build some simple linear models that include no transformations or interactions. Fit them, and determine their RMSE and $R^2$ on the both the training and test sets. Which of your models does the best?
5. Make partial correlation plots for each of the numeric variables in your model. Do you notice any significant non-linearities?
6. Include transformations and interactions of your variables, and build a more complex model that reflects your ideas about how the features of the asset determine its value. Determine its RMSE and $R^2$ on the training and test sets. How does the more complex model your build compare to the simpler ones?
7. Summarize your results from 1 to 6. Have you learned anything about overfitting and underfitting, or model selection?
8. If you have time, use the sklearn.linear_model.Lasso to regularize your model and select the most predictive features. Which does it select? What are the RMSE and $R^2$? We'll cover the Lasso later in detail in class.

In [22]:
# Chose the airbnb_hw.csv data set
# Load packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load data
df = pd.read_csv('https://raw.githubusercontent.com/dylanmulieri/linear_models/refs/heads/main/assignment/data/airbnb_hw.csv')

# 1
'''
Clean the data and perform some EDA and visualization to get to know the data set.
'''
# basic functions
display(df.head())
display(df.describe())
display(df.info())
display(df.shape)

# Change 'Price' from object to float64
df['Price'] = df['Price'].str.replace('$', '', regex=False) # Remove potential $
df['Price'] = df['Price'].str.replace(',', '', regex=False) # Remove potential space
df['Price'] = df['Price'].astype(float)
# info again to check
display(df.info()) # Worked!

# Take a look at missing data
display(df.isnull().sum())

# Drop nulls in 'Host Since' and 'Property Type'
df = df.dropna(subset=['Host Since', 'Property Type'])
# check
display(df.isnull().sum()) # worked!

# What is the difference between 'Review Scores Rating (bin)' and 'Review Scores Rating"?
display(df['Review Scores Rating (bin)'].unique())
display(df['Review Scores Rating'].unique())

#

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating
0,5162530,NaN,1 Bedroom in Prime Williamsburg,Brooklyn,Apartment,NaN,Entire home/apt,11249.0,1.0,1,0,145,NaN
1,33134899,NaN,"Sunny, Private room in Bushwick",Brooklyn,Apartment,NaN,Private room,11206.0,1.0,1,1,37,NaN
2,39608626,NaN,Sunny Room in Harlem,Manhattan,Apartment,NaN,Private room,10032.0,1.0,1,1,28,NaN
3,500,6/26/2008,Gorgeous 1 BR with Private Balcony,Manhattan,Apartment,NaN,Entire home/apt,10024.0,3.0,1,0,199,NaN
4,500,6/26/2008,Trendy Times Square Loft,Manhattan,Apartment,95.0,Private room,10036.0,3.0,1,39,549,96.0

,Host Id,Review Scores Rating (bin),Zipcode,Beds,Number of Records,Number Of Reviews,Review Scores Rating
count,3.047800e+04,22155.000000,30344.000000,30393.000000,30478.0,30478.000000,22155.000000
mean,1.273171e+07,90.738659,10584.854831,1.530089,1.0,12.018735,91.993230
std,1.190270e+07,9.059519,921.299397,1.015359,0.0,21.980703,8.850373
min,5.000000e+02,20.000000,1003.000000,0.000000,1.0,0.000000,20.000000
25%,2.701298e+06,85.000000,10017.000000,1.000000,1.0,0.000000,89.000000
50%,8.551693e+06,90.000000,10065.000000,1.000000,1.0,3.000000,94.000000
75%,2.120617e+07,100.000000,11216.000000,2.000000,1.0,13.000000,100.000000
max,4.303307e+07,100.000000,99135.000000,16.000000,1.0,257.000000,100.000000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30478 entries, 0 to 30477
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Host Id                     30478 non-null  int64
 1   Host Since                  30475 non-null  object
 2   Name                        30478 non-null  object
 3   Neighbourhood               30478 non-null  object
 4   Property Type               30475 non-null  object
 5   Review Scores Rating (bin)  22155 non-null  float64
 6   Room Type                   30478 non-null  object
 7   Zipcode                     30344 non-null  float64
 8   Beds                        30393 non-null  float64
 9   Number of Records           30478 non-null  int64
 10  Number Of Reviews           30478 non-null  int64
 11  Price                       30478 non-null  object
 12  Review Scores Rating        22155 non-null  float64
dtypes: float64(4), int64(3), object(6)
memory usage: 3.0+ MB

None

(30478, 13)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30478 entries, 0 to 30477
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Host Id                     30478 non-null  int64
 1   Host Since                  30475 non-null  object
 2   Name                        30478 non-null  object
 3   Neighbourhood               30478 non-null  object
 4   Property Type               30475 non-null  object
 5   Review Scores Rating (bin)  22155 non-null  float64
 6   Room Type                   30478 non-null  object
 7   Zipcode                     30344 non-null  float64
 8   Beds                        30393 non-null  float64
 9   Number of Records           30478 non-null  int64
 10  Number Of Reviews           30478 non-null  int64
 11  Price                       30478 non-null  float64
 12  Review Scores Rating        22155 non-null  float64
dtypes: float64(5), int64(3), object(5)
memory usage: 3.0+ MB

None

Host Id                          0
Host Since                       3
Name                             0
Neighbourhood                    0
Property Type                    3
Review Scores Rating (bin)    8323
Room Type                        0
Zipcode                        134
Beds                            85
Number of Records                0
Number Of Reviews                0
Price                            0
Review Scores Rating          8323
dtype: int64

Host Id                          0
Host Since                       0
Name                             0
Neighbourhood                    0
Property Type                    0
Review Scores Rating (bin)    8319
Room Type                        0
Zipcode                        134
Beds                            85
Number of Records                0
Number Of Reviews                0
Price                            0
Review Scores Rating          8319
dtype: int64

array([ nan,  95., 100.,  90.,  85.,  80.,  75.,  65.,  70.,  60.,  40.,
        50.,  20.,  55.,  45.,  30.])

array([ nan,  96., 100.,  94.,  90.,  98.,  93.,  91.,  97.,  95.,  99.,
        85.,  86.,  80.,  88.,  92.,  89.,  82.,  87.,  81.,  76.,  78.,
        83.,  66.,  84.,  72.,  79.,  60.,  40.,  62.,  74.,  77.,  50.,
        71.,  75.,  73.,  69.,  65.,  68.,  70.,  67.,  64.,  20.,  57.,
        58.,  43.,  63.,  55.,  47.,  53.,  49.,  30.])